//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IPayMentService")]
    public interface IPayMentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayMentService/AddPayee", ReplyAction="http://tempuri.org/IPayMentService/AddPayeeResponse")]
        void AddPayee(string Name, string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayMentService/AddPayee", ReplyAction="http://tempuri.org/IPayMentService/AddPayeeResponse")]
        System.Threading.Tasks.Task AddPayeeAsync(string Name, string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayMentService/PayBill", ReplyAction="http://tempuri.org/IPayMentService/PayBillResponse")]
        string PayBill(string PayId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayMentService/PayBill", ReplyAction="http://tempuri.org/IPayMentService/PayBillResponse")]
        System.Threading.Tasks.Task<string> PayBillAsync(string PayId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayMentService/UpdateBillPayment", ReplyAction="http://tempuri.org/IPayMentService/UpdateBillPaymentResponse")]
        void UpdateBillPayment(string PayId, string TransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayMentService/UpdateBillPayment", ReplyAction="http://tempuri.org/IPayMentService/UpdateBillPaymentResponse")]
        System.Threading.Tasks.Task UpdateBillPaymentAsync(string PayId, string TransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayMentService/RemovePayee", ReplyAction="http://tempuri.org/IPayMentService/RemovePayeeResponse")]
        void RemovePayee(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayMentService/RemovePayee", ReplyAction="http://tempuri.org/IPayMentService/RemovePayeeResponse")]
        System.Threading.Tasks.Task RemovePayeeAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPayMentServiceChannel : WpfApplication1.ServiceReference2.IPayMentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PayMentServiceClient : System.ServiceModel.ClientBase<WpfApplication1.ServiceReference2.IPayMentService>, WpfApplication1.ServiceReference2.IPayMentService {
        
        public PayMentServiceClient() {
        }
        
        public PayMentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PayMentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayMentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayMentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddPayee(string Name, string City) {
            base.Channel.AddPayee(Name, City);
        }
        
        public System.Threading.Tasks.Task AddPayeeAsync(string Name, string City) {
            return base.Channel.AddPayeeAsync(Name, City);
        }
        
        public string PayBill(string PayId) {
            return base.Channel.PayBill(PayId);
        }
        
        public System.Threading.Tasks.Task<string> PayBillAsync(string PayId) {
            return base.Channel.PayBillAsync(PayId);
        }
        
        public void UpdateBillPayment(string PayId, string TransId) {
            base.Channel.UpdateBillPayment(PayId, TransId);
        }
        
        public System.Threading.Tasks.Task UpdateBillPaymentAsync(string PayId, string TransId) {
            return base.Channel.UpdateBillPaymentAsync(PayId, TransId);
        }
        
        public void RemovePayee(string Id) {
            base.Channel.RemovePayee(Id);
        }
        
        public System.Threading.Tasks.Task RemovePayeeAsync(string Id) {
            return base.Channel.RemovePayeeAsync(Id);
        }
    }
}
